- name: add ssh key for mimir
  authorized_key:
    user: mimir
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF8sHk7Dd0OrFTJPIz2dlQyVs+hb5ZLMzJ1YeVckR2hE pavl default"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
